# Generated by Django 4.0.5 on 2022-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MartialSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassengerBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('human', models.BooleanField(default=False)),
                ('martial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stadelino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('human_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.humanseat')),
                ('martial_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.martialseat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spacer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('human_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.humanseat')),
                ('martial_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.martialseat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulletShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('human_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.humanseat')),
                ('martial_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.martialseat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
